DROP DATABASE IF EXISTS `registertest`;
CREATE DATABASE `registertest` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'registertest'@'localhost' IDENTIFIED BY 'xxx';
CREATE USER 'registertest'@'%' IDENTIFIED BY 'xxx';

CREATE USER 'registertestsu'@'localhost' IDENTIFIED BY 'xxx';
CREATE USER 'registertestsu'@'%' IDENTIFIED BY 'xxx';

REVOKE ALL PRIVILEGES ON * . * FROM 'registertest'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'registertest'@'%';

REVOKE ALL PRIVILEGES ON * . * FROM 'registertestsu'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'registertestsu'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON registertest.* TO 'registertest'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE ON registertest.* TO 'registertest'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON registertest.* TO 'registertestsu'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON registertest.* TO 'registertestsu'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;
